"""initial schema

Revision ID: 306d78b7eb3d
Revises: 
Create Date: 2026-08-09 14:53:24.617942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '306d78b7eb3d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_features'))
    )
    op.create_index(op.f('ix_features_key'), 'features', ['key'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('tenant_features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['feature_key'], ['features.key'], name=op.f('fk_tenant_features_feature_key_features'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_features_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_features')),
    sa.UniqueConstraint('tenant_id', 'feature_key', name='uq_tenant_features_tenant_feature')
    )
    op.create_index(op.f('ix_tenant_features_feature_key'), 'tenant_features', ['feature_key'], unique=False)
    op.create_index(op.f('ix_tenant_features_tenant_id'), 'tenant_features', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('tenant_admin', 'trainer', 'front_desk', name='user_role'), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_super_admin AND tenant_id IS NULL AND role IS NULL) OR (NOT is_super_admin AND tenant_id IS NOT NULL AND role IS NOT NULL)', name=op.f('ck_users_super_admin_or_tenant_scoped')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_id_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index('uq_users_super_admin_email', 'users', ['email'], unique=True, postgresql_where=sa.text('is_super_admin'))
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # --- Row Level Security: a second, database-enforced layer of tenant isolation. ---
    # FORCE is required because our app connects as the same role that owns these
    # tables (the role that ran this migration) -- without FORCE, Postgres exempts
    # the owning role from RLS entirely, silently defeating the whole point.
    for table in ("users", "tenant_features", "audit_logs"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (
                current_setting('app.bypass_rls', true) = 'true'
                -- Compare as text, not by casting the setting to uuid: Postgres
                -- custom GUCs revert to '' (not NULL) once touched by a SET LOCAL
                -- in an earlier transaction on a reused pooled connection, and
                -- casting '' to uuid raises a hard error -- one the planner can
                -- trigger even inside a supposedly-short-circuited AND/OR, since
                -- it may evaluate stable-function subexpressions like this cast
                -- independently of row-level boolean short-circuiting. Casting
                -- the (never-null) column to text instead never errors, for any
                -- value the setting holds.
                OR tenant_id::text = current_setting('app.tenant_id', true)
            )
            """
        )

    # --- Seed the feature catalog super-admin can toggle per tenant. ---
    op.execute(
        """
        INSERT INTO features (id, key, name, description) VALUES
            (gen_random_uuid(), 'class_scheduling', 'Class scheduling', 'Book and manage group class sessions'),
            (gen_random_uuid(), 'billing', 'Billing', 'Membership billing and invoicing'),
            (gen_random_uuid(), 'equipment_tracking', 'Equipment tracking', 'Track gym equipment inventory and maintenance')
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    for table in ("users", "tenant_features", "audit_logs"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_users_super_admin_email', table_name='users', postgresql_where=sa.text('is_super_admin'))
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenant_features_tenant_id'), table_name='tenant_features')
    op.drop_index(op.f('ix_tenant_features_feature_key'), table_name='tenant_features')
    op.drop_table('tenant_features')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_features_key'), table_name='features')
    op.drop_table('features')
    # ### end Alembic commands ###
